PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>

# Consulta: Quantidade de publicações por quartil
# Objetivo: verificar a distribuição das publicações em Q1, Q2, Q3 e Q4.

SELECT ?quartil (COUNT(DISTINCT ?producao) AS ?total_producoes)
WHERE {
  ?producao a cti:Producao_Cientifica ;
            cti:publicada_em ?veiculo .

  ?veiculo a cti:Veiculo_Publicacao ;
           cti:ds_quartil ?quartil .

  FILTER(?quartil != "")
  FILTER(?quartil != "Sem_Quartil")
  FILTER(?quartil != "Não_Encontrado")
}
GROUP BY ?quartil
ORDER BY ?quartil