PREFIX cti: <http://gic.ufrpe.br/cti/vocabulary/cti#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Consulta: Top veículos de publicação por CiteScore
# Objetivo: identificar os veículos de maior impacto presentes na base.

SELECT ?veiculo ?identificador ?quartil ?citescore
WHERE {
  ?v a cti:Veiculo_Publicacao ;
     cti:cd_identificador_veiculo ?identificador ;
     cti:nr_citescore ?citescore ;
     cti:ds_quartil ?quartil .

  OPTIONAL {
    ?v cti:nm_veiculo_publicacao ?veiculo .
  }

  FILTER(?citescore != "0.0")
  FILTER(?citescore != "")
  FILTER(?citescore != "None")
  FILTER(?citescore != "Não_Encontrado")
}
ORDER BY DESC(xsd:decimal(?citescore))
LIMIT 20